[project]
name = "HostSub_GP"
version = "0.1.0"
description = "Host Subtraction with Gaussian Processes"
authors = [{ name = "Chang Liu" }]
requires-python = ">=3.12"
dependencies = [
    "tinygp",
    "jaxopt",
    "astroquery",
    "reproject",
    "astropy>=7.0",
    "matplotlib>=3.10.5",
]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["astronomy", "gaussian processes", "host subtraction"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]

[project.optional-dependencies]
pypeit = ["pypeit"]

[project.scripts]
hostsub = "hostsub_gp.scripts.hostsub:HostSub.entry_point"
hostsub_setup = "hostsub_gp.scripts.hostsub_setup:HostSubSetup.entry_point"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.package-data]
hostsub_gp = ["data/*.csv"]
