# HEADER.toml

[basic]
# Instrument specific parameters (MUSE)
pixel_scale = 0.2 # arcsec/pixel
spec_resln = 2.7  # Angstroms
slit_len = 30.0   # arcsec
slit_wid = 1.0    # arcsec
# Model specific parameters
host_wid = 10.0 # arcsec
mask_wid = 2.0 # in spat_resln
position_angle = 90.0 # degrees
spec_range = [
    5500,
    9200,
] # Angstroms - Edge (throughput = half maximum) of the PS1 r and z filters

[basic.spiral]
PI = "TANVIR, NIAL"
program_id = "0100.D-0649"
object = "LCRS B110709.2-121854"
z = 0.036932

[spec_model.spiral]
spat_resln = 0.68
sky_region = [-10, 10]

[slit_range.spiral]
row = [140, 200]
col = [160, 165]
mask_offset = [-50, 50]

[basic.elliptical]
PI = "Johnston"
program_id = "099.B-0411(A)"
object = "J205050.78-004350.85"
z = 0.0571

[spec_model.elliptical]
spat_resln = 0.78
sky_region = [-10, 10]

[slit_range.elliptical]
row = [140, 160]
col = [150, 170]
mask_offset = [-5, 6]
